app/views/views.py
from flask import Blueprint, render_template, session, redirect, url_for, request, jsonify
from app.models.products import Products
from app.models.address import Address
from app.models.users import Users
from app.models.orders import Orders
from app.models.tickets import Tickets
from app import db

from flask_cors import cross_origin

views = Blueprint('views', __name__, url_prefix="/")

@views.route('/')
@cross_origin()
def login():
    try:
        return render_template("/login/login.html")
    except Exception as e:
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

@views.route('/dashboard')
@cross_origin()
def dashboard():
    try:
        products = Products.query.all()
        return render_template("/dashboard/dashboard.html", products=products, user_id=session.get('user_id'))
    except Exception as e:
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

@views.route('/profile')
@cross_origin()
def profile():
    try:
        user_id = session.get('user_id')
        user = Users.query.filter_by(id=user_id).first()
        order_query = f"select p.image, p.name, o.amount from products p right join orders o on o.user_id={user['id']} and p.id=o.product_id;"
        orders = db.engine.execute(order_query).all()
        tickets = Tickets.query.filter_by(user_id=user.id).all()
        addresses = Address.query.filter_by(user_id=user.id).all()
        return render_template("/profile/profile.html", user=user, orders=orders, addresses=addresses, tickets=tickets, user_id=user.id)
    except Exception as e:
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

@views.route('/order')
@cross_origin()
def order():
    try:
        product_id = request.args.get("id")
        if not product_id:
            return jsonify({
                "message": "No product for purchase!",
                "status": "error"
            }), 400
        product = Products.query.filter_by(id=product_id).first()
        addresses = Address.query.filter_by(user_id=user.id).all()
        return render_template("/order/order.html", product=product, addresses=addresses, user_id=session.get('user_id'))
    except Exception as e:
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

@views.route("/help")
@cross_origin()
def help_page():
    try:
        return render_template("/help/help.html", user_id=session.get('user_id'))
    except Exception as e:
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

@views.route("/editor")
@cross_origin()
def editor():
    try:
        return render_template("/editor/editor.html")
    except Exception as e:
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

app/templates/main.jinja
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;900&display=swap" rel="stylesheet">

    <!-- Sweet Alert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include("main_script.jinja") %}
    {% include("main_style.jinja") %}
</head>

<body>
    <div class="main-container">
        <nav class="navbar fixed-top navbar-expand navbar-light" style="background: #442ea6;">
            <div class="navbar-collapse" id="navbarsExample02">
                <a class="navbar-brand pl-5 pr-5" href="/">
                    <span style="font-size: 2em; color: white;"><b>Toy-e-Wagon</b></span>
                </a>
                <div>
                    <div class="searchInputWrapper">
                        <input class="searchInput" type="text" placeholder='Search'>
                        <i class="searchInputIcon fa fa-search"></i>
                        </input>
                    </div>
                </div>
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item align-self-center" id="dashboard_navigator">
                        <a class="nav-link" href="{{url_for('views.dashboard')}}">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2">
                                    <i class="fa fa-tachometer nav-icon"></i>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                                    <p class="nav-text">Dashboard</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item align-self-center" id="profile_navigator">
                        <a class="nav-link" href="{{url_for('views.profile')}}?id={{user_id}}">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2">
                                    <i class="fa fa-user nav-icon"></i>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                                    <p class="nav-text">Profile</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item align-self-center">
                        <a class="nav-link" onclick="logout_user()">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2">
                                    <i class="fa fa-sign-out nav-icon"></i>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                                    <p class="nav-text">Logout</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('views.help_page')}}">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2 help-button">
                                    <i class="fa fa-question-circle-o nav-icon"></i>
                                    <span class="nav-text p-3" style="font-size: 1.5em;">Help</span>
                                </div>
                            </div>
                        </a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-md-0"> </form>
            </div>
        </nav>
    </div>
    <div>
        {% block main %}{% endblock %}
    </div>
</body>

</html>

app/templates/main_script.jinja
<script>
    function logout_user() {
        $.ajax({
            url: "{{url_for('api.logout')}}",
            type: 'post',
            success: function (result) {
                window.location.href = "{{url_for('views.login')}}";
            },
            error: function (result) {
                alert(result.responseJSON.message);
            }
        });
    }
</script>

app/templates/main_style.jinja
<style>
    body {
        direction: ltr;
        text-align:left;
        background-color: #f0f1f3;
        font-family: 'Fira Sans', sans-serif;
        overflow-x: hidden;
    }
    .blur {
        filter: blur(5px);
        -webkit-filter: blur(5px);
        -moz-filter: blur(5px);
        -o-filter: blur(5px);
        -ms-filter: blur(5px);
    }
    #loader {
        position: fixed;
        display: none;
        align-items: center;
        width: 50%;
        top: 30%;
        left: 35%;
        z-index: 999;
    }
    .loading-gif {
        width: 50%;
        height: auto;
    }
    .navbar-light .navbar-nav .active>.nav-link, .navbar-light .navbar-nav .nav-link.active, .navbar-light .navbar-nav .nav-link.show, .navbar-light .navbar-nav .show>.nav-link {
        color: #72f588;
    }
    .navbar-light .navbar-nav .nav-link {
        color: white;
    }

    .searchInputWrapper {
        position: relative;
    }

    .searchInput {
        width: 20rem;
        height: 2rem;
        padding: 0 1rem; 
        border-radius: 2rem;
        border: none;
        background-color: #c5b5e5;
        transition: transform 0.1s ease-in-out;
    }

    ::placeholder {
        color: black;
    }

    :focus::placeholder {
        text-indent: -999px
    }

    .searchInput:focus {
        outline: none;
        transform: scale(1.1);
        transition: all 0.1s ease-in-out;
    }

    .searchInputIcon {
        position: absolute;
        right: 0.8rem;
        top: 0.5rem;
        color: black;
        transition: all 0.1s ease-in-out;
    }

    .container:focus-within > 
    .searchInputWrapper > .searchInputIcon {
        right: 0.2rem;
    }

    .nav-icon {
        font-size: 2em;
    }

    .nav-text {
        font-size: 1em;
    }

    .help-button {
        background-color: #673dcf;
        padding: 0.5em 1em;
        border-radius: 2em;
    }
</style>